name: tflite_tts
description: A new flutter plugin project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  plugin_platform_interface: ^2.0.0
  flutter:
    sdk: flutter
  path_provider: ^2.0.0
  path: 
  tuple: ^2.0.0
  flutter_mmap_stream:
    git:
      url: git@github.com:nmfisher/flutter_mmap_stream.git
  flutter_tflite:
    #git:
    #  url: git@github.com:nmfisher/flutter_tflite.git
    path: ../flutter_tflite

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: TfliteTtsPlugin
      android:
        pluginClass: TfliteTtsPlugin
        package: com.avinium.tflite_tts

  