name: flutter_tflite_tts_plugin
description: A Flutter plugin for text-to-speech from a TFLite model.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  plugin_platform_interface: ^2.0.0
  flutter:
    sdk: flutter
  path_provider: 
  path: 
  tuple: ^2.0.0
  flutter_mmap_stream:
    path: ../flutter_mmap_stream
  flutter_tflite:
    path: ../flutter_tflite

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: TfliteTtsPlugin
      android:
        pluginClass: TfliteTtsPlugin
        package: com.avinium.flutter_tflite_tts_plugin

  
